galaxy_info:
  author: João Carlos Mendes
  description: Just a role to WRF V4.0 installation
  company: www.squitter.com.br
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
  - name: CentOS
    versions:
    - 7
  galaxy_tags: []
dependencies: []
